name: Ajout d'un commentaire

on:
  pull_request:
    types: [opened, closed]

env:
  USERS: ${{ github.actor }}
  USERS_ID: ${{ github.actor_id }}
  REF: ${{ github.head_ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  Comment_PR:
    name: Ajout d'un commentaire
    runs-on: ubuntu-latest

    steps:
      - if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened'}}
        run: gh pr comment $PR_URL --body "Une PR a été ouverte."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - if: ${{ github.event.pull_request.merged == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}  
        run: gh pr comment $PR_URL --body "La PR a été mergée."
  
  Readme-update:
    name: Mise à jour du fichier README
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout du code source
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clonage du dépôt distant
        run: git clone https://github.com/boutignyb/My-repo.git

      - name: Création de la branche feature/readme
        run: |
          cd $GITHUB_WORKSPACE/My-repo
          git checkout -b feature/readme

      - name: Mise à jour du README.md
        run: |
          cd $GITHUB_WORKSPACE/My-repo
          echo 'Une mise à jour a été effectuée par $USERS ($USERS_ID) depuis la branche $REF.' > README.md

      - name: Ajout du fichier modifié
        run: |
          cd $GITHUB_WORKSPACE/My-repo
          git add README.md

      - name: Commit des changements
        run: |
          cd $GITHUB_WORKSPACE/My-repo
          git config --global user.name "$USERS"
          git config --global user.email "$USERS_ID@users.noreply.github.com"
          git commit -m "Mise à jour du README.md par $USERS"

      - name: Push de la branche feature/readme
        run: |
          cd $GITHUB_WORKSPACE/My-repo
          git config --global user.name "$USERS"
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/boutignyb/My-repo.git
          git push origin feature/readme

      - name: Création de la Pull Request pour la mise à jour du README
        run: gh pr create --base main --head feature/readme --title "Mise à jour du README" --body "Cette PR contient une mise à jour automatique du README."

      - name: Suppression de la branche locale
        run: |
          cd $GITHUB_WORKSPACE/My-repo
          git branch -D feature/readme

      - name: Retour à la branche principale
        run: |
          cd $GITHUB_WORKSPACE/My-repo
          git checkout main

    