name: Ajout d'un commentaire

on:
  pull_request:
    types: [opened, closed]

env:
  USERS: ${{ github.actor }}
  USERS_ID: ${{ github.actor_id }}
  REF: ${{ github.head_ref }}

permissions:
  pull-requests: write

jobs:
  Comment_PR:
    name: Ajout d'un commentaire
    runs-on: ubuntu-latest

    steps:
      - if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened'}}
        run: gh pr comment $PR_URL --body "Une PR a été ouverte."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - if: ${{ github.event.pull_request.merged == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}  
        run: gh pr comment $PR_URL --body "La PR a été mergée."
  
  Readme-update:
    name: Mise à jour du fichier README
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Récupération du dépôt
        run: git clone https://github.com/boutignyb/My-repo.git

      - name: Création d'une branche feature/readme
        run: |
          cd $GITHUB_WORKSPACE/My-repo
          git checkout -b feature/readme

      - name: Mise à jour du README.md
        run: |
          cd $GITHUB_WORKSPACE/My-repo
          echo 'Une mise à jour a été effectuée par $USERS ($USERS_ID) depuis la branche $REF.' > README.md

      - name: Ajour du contenu du README
        run: |
          cd $GITHUB_WORKSPACE/My-repo
          git add .
      
      - name: Commit du Readme
        run: |
          cd $GITHUB_WORKSPACE/My-repo
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.action }}@.github.com
          git config --global url.git@github.com:boutignyb/My-repo.git
          git commit -m "Mise à jour de README.md"

      - name: Push de la branche en cours
        run: |
          cd $GITHUB_WORKSPACE/My-repo
          git push origin feature/readme

      - name: PR de la branche
        run: git pull_request_auto_merged
      
      - name: Suppression de la branche
        run: git branch -D feature/readme
      
      - name: Retour à la branche @main
        run : git checkout main
