name: Ajout d'un commentaire

on:
  pull_request:
    types: [opened, closed]

permissions:
  pull-requests: write

jobs:
  Comment_PR:
    name: Ajout d'un commentaire
    runs-on: ubuntu-latest

    steps:
      - if: ${{ github.event_name == 'pull_request' && github.event.pull_request.state == 'opened'}}
        run: gh pr comment $PR_URL --body "Une PR a été ouverte."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - if: ${{ github.event.pull_request.merged == true }}
        run: gh pr comment $PR_URL --body "La PR a été mergée."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}